name: pocket_ledger_app
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.6.1

  # Data Modeling & Codegen
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # Functional Extensions & Methods
  dartz: ^0.10.1

  # Networking
  dio: ^5.4.3+1
  retrofit: ^4.1.0

  # Routing
  auto_route: ^8.1.3

  # Local Persistence
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3

  # Utilities
  uuid: ^4.4.0
  image_picker: ^1.1.1
  file_picker: ^8.0.3

  # Charts
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

  # Codegen Tools
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  retrofit_generator: ^8.1.0
  auto_route_generator: ^8.0.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/icon/logo.png' # path to your icon image
